const SCREENS = {
  ABOUT: 'ABOUT',
  INTRO: 'INTRO',
  LOGIN: 'LOGIN',
  SETTING: 'SETTING',
  SIGNUP: 'SIGNUP',
  HOME: 'HOME',
  LANGUAGE: 'LANGUAGE',
  ORDERS: 'ORDERS',
  WISHLIST: 'WISHLIST',
  PROFILE: 'PROFILE',
};

export default SCREENS;
